apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: workshop-alerts
  namespace: observability
spec:
  groups:
  - name: api.rules
    rules:
    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{app="my-api",status=~"5.."}[5m])) / sum(rate(http_requests_total{app="my-api"}[5m])) > 0.02
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: ">2% d’erreurs 5xx sur 10m"
        description: "Surveille le taux d'erreurs HTTP 5xx sur l'API my-api."
    - alert: PodHighRestarts
      expr: increase(kube_pod_container_status_restarts_total{app="my-api"}[10m]) > 5
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Redémarrages anormaux des pods"
        description: "Alerte si un pod redémarre plus de 5 fois sur 15 min."
