apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapress-api
  namespace: datapress-recette
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datapress-api
  template:
    metadata:
      labels:
        app: datapress-api
    spec:
      containers:
        - name: api
          image: datapress-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DP_ENV
              valueFrom:
                configMapKeyRef:
                  name: datapress-config
                  key: DP_ENV
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: datapress-config
                  key: WELCOME_MESSAGE
            - name: API_FAKE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: datapress-secret
                  key: API_FAKE_TOKEN
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "256Mi"
